services:
  - type: web
    name: tank-world-war
    env: node
    buildCommand: npm install && npm run build
    startCommand: node server/index.js
    envVars:
      - key: NODE_VERSION
        value: 18
    plan: free
